# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Vu_8x8btGhF2DY45oK9Z8cGflwnhBy-
"""

def luas_persegi_panjang(panjang,lebar):
  return panjang*lebar
print(luas_persegi_panjang(30,40))

angka = [1,2,3,4,5,6,7,8,9,10]
for i in range(len(angka)):
  if angka[i] % 2 == 0:
    print(angka[i])

Mahasiswa = {"nama" : "Shada", "nim" : "247","jurusan" : "Informatika"}
print(Mahasiswa)